#!/bin/bash

# navigate to the root directory of the repository
git_root=$(git rev-parse --show-toplevel)
cd $git_root

# installation
npm init
npm install jest --save-dev
sed -i '' 's/"test".*/"test": "jest"/' package.json

# configuring Jest to support ES6 commands: import & export
npm install @babel/preset-env --save-dev
# if .babelrc already exists, prompt the user to add the appropriate presets
if [ -f .babelrc ]; then
  echo '* NOTE: Add "@babel/preset-env" to .babelrc presets, if necessary.'
# if .babelrc does not exist (most likely scenario), create one with the appropriate presets
else
  cat << EOF > .babelrc
{
  "presets": ["@babel/preset-env"]
}
EOF
fi
